application:
  port: 8000
  base_url: "http://127.0.0.1"
  hmac_secret: "Disselavaccaalmulo"
database:
  host: "localhost"
  port: 5433
  username: "xx"
  password: "sxdcfvgb"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "luca@xxmiglia.com"
  authorization_token: "829c5902-791d-4949-b3a7-fb0711efd663"
  timeout_milliseconds: 10000