application:
  port: 8000
database:
  host: "localhost"
  port: 5433
  username: "xx"
  password: "sxdcfvgb"
  database_name: "newsletter"
email_client:
  base_url: "https://api.postmarkapp.com"
  sender_email: "luca@xxmiglia.com"